# coding: utf-8

# flake8: noqa
"""
    Kadaster - BRK-Kadasterpersonen-Bevragen API

    D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van informatie over bij het Kadaster geregistreerde natuurlijk personen en niet-natuurlijk personen.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.adres import Adres
from openapi_client.models.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.models.bad_request_foutbericht_all_of import BadRequestFoutberichtAllOf
from openapi_client.models.datum_onvolledig import DatumOnvolledig
from openapi_client.models.foutbericht import Foutbericht
from openapi_client.models.geboorte import Geboorte
from openapi_client.models.geslacht_enum import GeslachtEnum
from openapi_client.models.hal_collection_links import HalCollectionLinks
from openapi_client.models.hal_link import HalLink
from openapi_client.models.heeft_partnerschap import HeeftPartnerschap
from openapi_client.models.invalid_params import InvalidParams
from openapi_client.models.kadaster_natuurlijk_persoon import KadasterNatuurlijkPersoon
from openapi_client.models.kadaster_natuurlijk_persoon_all_of import KadasterNatuurlijkPersoonAllOf
from openapi_client.models.kadaster_natuurlijk_persoon_hal import KadasterNatuurlijkPersoonHal
from openapi_client.models.kadaster_natuurlijk_persoon_hal_all_of import KadasterNatuurlijkPersoonHalAllOf
from openapi_client.models.kadaster_natuurlijk_persoon_hal_collectie import KadasterNatuurlijkPersoonHalCollectie
from openapi_client.models.kadaster_natuurlijk_persoon_hal_collectie_embedded import KadasterNatuurlijkPersoonHalCollectieEmbedded
from openapi_client.models.kadaster_niet_natuurlijk_persoon import KadasterNietNatuurlijkPersoon
from openapi_client.models.kadaster_niet_natuurlijk_persoon_all_of import KadasterNietNatuurlijkPersoonAllOf
from openapi_client.models.kadaster_niet_natuurlijk_persoon_hal import KadasterNietNatuurlijkPersoonHal
from openapi_client.models.kadaster_niet_natuurlijk_persoon_hal_collectie import KadasterNietNatuurlijkPersoonHalCollectie
from openapi_client.models.kadaster_niet_natuurlijk_persoon_hal_collectie_embedded import KadasterNietNatuurlijkPersoonHalCollectieEmbedded
from openapi_client.models.kadaster_persoon import KadasterPersoon
from openapi_client.models.kadaster_persoon_all_of import KadasterPersoonAllOf
from openapi_client.models.kadaster_persoon_links import KadasterPersoonLinks
from openapi_client.models.naam import Naam
from openapi_client.models.overlijden import Overlijden
from openapi_client.models.persoon_basis import PersoonBasis
from openapi_client.models.postadres import Postadres
from openapi_client.models.postadres_all_of import PostadresAllOf
from openapi_client.models.waardelijst import Waardelijst
