/* 
 * Kadaster - BRK-Kadasterpersonen-Bevragen API
 *
 * Deze API verstrekt informatie over bij het kadaster registreerde personen die (als het goed is) niet zijn geregistreerd in het Handelsregister of de Basisregistratie Personen (inclusief de Registratie Niet Ingezetenen). Het gaat meestal over personen die in het buitenland verblijven of organisaties die in het buitenland gevestigd zijn, en een zakelijk recht hebben op een kadastraal onroerende zaak. Personen in de basisregistratie kadaster worden niet geactualiseerd. De API verstrekt gegevens van personen op het moment van vestiging van het zakelijk recht.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Een bij het kadaster geregistreerde niet natuurlijke persoon, al dan niet ingeschreven in het handelsregister. Kadasternietnatuurlijkpersonen worden niet geactualiseerd.  Waardelijst in deze component : [beschikkingsbevoegdheid](http://www.kadaster.nl/schemas/waardelijsten/Beschikkingsbevoegdheid/) en [rechtsvorm](http://www.kadaster.nl/schemas/waardelijsten/Rechtsvorm/)
    /// </summary>
    [DataContract]
    public partial class KadasterNietNatuurlijkPersoonAllOf :  IEquatable<KadasterNietNatuurlijkPersoonAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KadasterNietNatuurlijkPersoonAllOf" /> class.
        /// </summary>
        /// <param name="statutaireNaam">statutaireNaam.</param>
        /// <param name="statutaireZetel">statutaireZetel.</param>
        /// <param name="rechtsvorm">rechtsvorm.</param>
        /// <param name="kvkNummer">kvkNummer.</param>
        /// <param name="rsin">rsin.</param>
        public KadasterNietNatuurlijkPersoonAllOf(string statutaireNaam = default(string), string statutaireZetel = default(string), Waardelijst rechtsvorm = default(Waardelijst), string kvkNummer = default(string), string rsin = default(string))
        {
            this.StatutaireNaam = statutaireNaam;
            this.StatutaireZetel = statutaireZetel;
            this.Rechtsvorm = rechtsvorm;
            this.KvkNummer = kvkNummer;
            this.Rsin = rsin;
        }
        
        /// <summary>
        /// Gets or Sets StatutaireNaam
        /// </summary>
        [DataMember(Name="statutaireNaam", EmitDefaultValue=false)]
        public string StatutaireNaam { get; set; }

        /// <summary>
        /// Gets or Sets StatutaireZetel
        /// </summary>
        [DataMember(Name="statutaireZetel", EmitDefaultValue=false)]
        public string StatutaireZetel { get; set; }

        /// <summary>
        /// Gets or Sets Rechtsvorm
        /// </summary>
        [DataMember(Name="rechtsvorm", EmitDefaultValue=false)]
        public Waardelijst Rechtsvorm { get; set; }

        /// <summary>
        /// Gets or Sets KvkNummer
        /// </summary>
        [DataMember(Name="kvkNummer", EmitDefaultValue=false)]
        public string KvkNummer { get; set; }

        /// <summary>
        /// Gets or Sets Rsin
        /// </summary>
        [DataMember(Name="rsin", EmitDefaultValue=false)]
        public string Rsin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KadasterNietNatuurlijkPersoonAllOf {\n");
            sb.Append("  StatutaireNaam: ").Append(StatutaireNaam).Append("\n");
            sb.Append("  StatutaireZetel: ").Append(StatutaireZetel).Append("\n");
            sb.Append("  Rechtsvorm: ").Append(Rechtsvorm).Append("\n");
            sb.Append("  KvkNummer: ").Append(KvkNummer).Append("\n");
            sb.Append("  Rsin: ").Append(Rsin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as KadasterNietNatuurlijkPersoonAllOf);
        }

        /// <summary>
        /// Returns true if KadasterNietNatuurlijkPersoonAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of KadasterNietNatuurlijkPersoonAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KadasterNietNatuurlijkPersoonAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StatutaireNaam == input.StatutaireNaam ||
                    (this.StatutaireNaam != null &&
                    this.StatutaireNaam.Equals(input.StatutaireNaam))
                ) && 
                (
                    this.StatutaireZetel == input.StatutaireZetel ||
                    (this.StatutaireZetel != null &&
                    this.StatutaireZetel.Equals(input.StatutaireZetel))
                ) && 
                (
                    this.Rechtsvorm == input.Rechtsvorm ||
                    (this.Rechtsvorm != null &&
                    this.Rechtsvorm.Equals(input.Rechtsvorm))
                ) && 
                (
                    this.KvkNummer == input.KvkNummer ||
                    (this.KvkNummer != null &&
                    this.KvkNummer.Equals(input.KvkNummer))
                ) && 
                (
                    this.Rsin == input.Rsin ||
                    (this.Rsin != null &&
                    this.Rsin.Equals(input.Rsin))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StatutaireNaam != null)
                    hashCode = hashCode * 59 + this.StatutaireNaam.GetHashCode();
                if (this.StatutaireZetel != null)
                    hashCode = hashCode * 59 + this.StatutaireZetel.GetHashCode();
                if (this.Rechtsvorm != null)
                    hashCode = hashCode * 59 + this.Rechtsvorm.GetHashCode();
                if (this.KvkNummer != null)
                    hashCode = hashCode * 59 + this.KvkNummer.GetHashCode();
                if (this.Rsin != null)
                    hashCode = hashCode * 59 + this.Rsin.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
