# coding: utf-8

# flake8: noqa

"""
    Kadaster - BRK-Kadasterpersonen-Bevragen API

    Deze API verstrekt informatie over bij het kadaster registreerde personen die (als het goed is) niet zijn geregistreerd in het Handelsregister of de Basisregistratie Personen (inclusief de Registratie Niet Ingezetenen). Het gaat meestal over personen die in het buitenland verblijven of organisaties die in het buitenland gevestigd zijn, en een zakelijk recht hebben op een kadastraal onroerende zaak. Personen in de basisregistratie kadaster worden niet geactualiseerd. De API verstrekt gegevens van personen op het moment van vestiging van het zakelijk recht.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.kadaster_natuurlijk_personen_api import KadasterNatuurlijkPersonenApi
from openapi_client.api.kadaster_niet_natuurlijk_personen_api import KadasterNietNatuurlijkPersonenApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.adres import Adres
from openapi_client.models.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.models.bad_request_foutbericht_all_of import BadRequestFoutberichtAllOf
from openapi_client.models.datum_onvolledig import DatumOnvolledig
from openapi_client.models.foutbericht import Foutbericht
from openapi_client.models.geboorte import Geboorte
from openapi_client.models.geslacht_enum import GeslachtEnum
from openapi_client.models.hal_collection_links import HalCollectionLinks
from openapi_client.models.hal_link import HalLink
from openapi_client.models.heeft_partnerschap import HeeftPartnerschap
from openapi_client.models.invalid_params import InvalidParams
from openapi_client.models.kadaster_natuurlijk_persoon import KadasterNatuurlijkPersoon
from openapi_client.models.kadaster_natuurlijk_persoon_all_of import KadasterNatuurlijkPersoonAllOf
from openapi_client.models.kadaster_natuurlijk_persoon_hal import KadasterNatuurlijkPersoonHal
from openapi_client.models.kadaster_natuurlijk_persoon_hal_all_of import KadasterNatuurlijkPersoonHalAllOf
from openapi_client.models.kadaster_natuurlijk_persoon_hal_collectie import KadasterNatuurlijkPersoonHalCollectie
from openapi_client.models.kadaster_natuurlijk_persoon_hal_collectie_embedded import KadasterNatuurlijkPersoonHalCollectieEmbedded
from openapi_client.models.kadaster_niet_natuurlijk_persoon import KadasterNietNatuurlijkPersoon
from openapi_client.models.kadaster_niet_natuurlijk_persoon_all_of import KadasterNietNatuurlijkPersoonAllOf
from openapi_client.models.kadaster_niet_natuurlijk_persoon_hal import KadasterNietNatuurlijkPersoonHal
from openapi_client.models.kadaster_niet_natuurlijk_persoon_hal_collectie import KadasterNietNatuurlijkPersoonHalCollectie
from openapi_client.models.kadaster_niet_natuurlijk_persoon_hal_collectie_embedded import KadasterNietNatuurlijkPersoonHalCollectieEmbedded
from openapi_client.models.kadaster_persoon import KadasterPersoon
from openapi_client.models.kadaster_persoon_all_of import KadasterPersoonAllOf
from openapi_client.models.kadaster_persoon_links import KadasterPersoonLinks
from openapi_client.models.naam import Naam
from openapi_client.models.overlijden import Overlijden
from openapi_client.models.persoon_basis import PersoonBasis
from openapi_client.models.postadres import Postadres
from openapi_client.models.postadres_all_of import PostadresAllOf
from openapi_client.models.waardelijst import Waardelijst

